import { Inter, Quicksand } from "next/font/google";
import "../styles/globals.scss";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/footer/Footer";


const inter = Inter({ subsets: ["latin"] });
const quickSand = Quicksand({ subsets: ["latin"] });
export const metadata = {
  title: "Aqua Cainta Resort",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quickSand.className}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
