import { Inter, Quicksand } from "next/font/google";
import "../styles/globals.scss";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/footer/Footer";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });
const quickSand = Quicksand({ subsets: ["latin"] });
export const metadata = {
  title: "Aqua Cainta Resort",
  description: "Generated by create next app",
};

export default function RootLayout({ children, showNavAndFooter = true }) {
  return (
    <html lang="en">
      <body className={quickSand.className}>
        <AuthProvider>
          <div className="container">
           { showNavAndFooter && <Navbar />}
            {children}
            { showNavAndFooter && <Footer />}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
